[package]
name = "pagerduty-rs"
version = "0.0.1"
authors = ["Archis Gore <archis@polyverse.com>"]
edition = "2018"
license-file = "LICENSE"
categories = ["pagerduty", "alerting"]
keywords = ["pagerduty", "alerts", "events", "incidents", "monitoring"]
readme = "README.md"
repository = "https://github.com/polyverse/pagerduty-rs"

description = """PagerDuty API from Rust."""


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"]}
serde = "1.0.117"
serde_json = "1.0.59"
url = "2.2.0"
ureq = "1.5.2"
rand = "0.7.3"

[dev-dependencies]
assert_matches = "1.4.0"
pretty_assertions = "0.6.1"
